/*
 * My Service API
 * A Spring Boot service archetype
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: core-starter@astreya.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ModelApiResponse
 */
class ModelApiResponseTest {
    private final ModelApiResponse model = new ModelApiResponse();

    /**
     * Model tests for ModelApiResponse
     */
    @Test
    void testModelApiResponse() {
        // TODO: test ModelApiResponse
    }

    /**
     * Test the property 'success'
     */
    @Test
    void successTest() {
        // TODO: test success
    }

    /**
     * Test the property 'message'
     */
    @Test
    void messageTest() {
        // TODO: test message
    }

    /**
     * Test the property 'data'
     */
    @Test
    void dataTest() {
        // TODO: test data
    }

}
