/*
 * My Service API
 * A Spring Boot service archetype
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: core-starter@astreya.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Sample
 */
class SampleTest {
    private final Sample model = new Sample();

    /**
     * Model tests for Sample
     */
    @Test
    void testSample() {
        // TODO: test Sample
    }

    /**
     * Test the property 'id'
     */
    @Test
    void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'createdBy'
     */
    @Test
    void createdByTest() {
        // TODO: test createdBy
    }

    /**
     * Test the property 'createdOn'
     */
    @Test
    void createdOnTest() {
        // TODO: test createdOn
    }

    /**
     * Test the property 'modifiedBy'
     */
    @Test
    void modifiedByTest() {
        // TODO: test modifiedBy
    }

    /**
     * Test the property 'modifiedOn'
     */
    @Test
    void modifiedOnTest() {
        // TODO: test modifiedOn
    }

    /**
     * Test the property 'status'
     */
    @Test
    void statusTest() {
        // TODO: test status
    }

}
