/*
 * My Service API
 * A Spring Boot service archetype
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: core-starter@astreya.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * API tests for DebugControllerApi
 */
@Disabled
public class DebugControllerApiTest {

    private final DebugControllerApi api = new DebugControllerApi();

    
    /**
     * 
     *
     * 
     */
    @Test
    public void debugOpenAPITest()  {
        // uncomment below to test the function
        //String response = api.debugOpenAPI().block();

        // TODO: test validations
    }
    
}
