/*
 * My Service API
 * A Spring Boot service archetype
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: core-starter@astreya.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.model.ModelApiResponse;
import org.openapitools.client.model.Sample;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * API tests for SampleControllerApi
 */
@Disabled
public class SampleControllerApiTest {

    private final SampleControllerApi api = new SampleControllerApi();

    
    /**
     * 
     *
     * 
     */
    @Test
    public void createSampleTest()  {
        // uncomment below to test the function
        //String xTenantID = null;
        //String xUserID = null;
        //String authToken = null;
        //Sample sample = null;
        //ModelApiResponse response = api.createSample(xTenantID, xUserID, authToken, sample).block();

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     */
    @Test
    public void deleteSampleTest()  {
        // uncomment below to test the function
        //Long id = null;
        //String xTenantID = null;
        //String xUserID = null;
        //String authToken = null;
        //ModelApiResponse response = api.deleteSample(id, xTenantID, xUserID, authToken).block();

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     */
    @Test
    public void getAllSamplesTest()  {
        // uncomment below to test the function
        //String xTenantID = null;
        //String xUserID = null;
        //String authToken = null;
        //ModelApiResponse response = api.getAllSamples(xTenantID, xUserID, authToken).block();

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     */
    @Test
    public void getSampleByIdTest()  {
        // uncomment below to test the function
        //Long id = null;
        //String xTenantID = null;
        //String xUserID = null;
        //String authToken = null;
        //ModelApiResponse response = api.getSampleById(id, xTenantID, xUserID, authToken).block();

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     */
    @Test
    public void updateSampleTest()  {
        // uncomment below to test the function
        //Long id = null;
        //String xTenantID = null;
        //String xUserID = null;
        //String authToken = null;
        //Sample sample = null;
        //ModelApiResponse response = api.updateSample(id, xTenantID, xUserID, authToken, sample).block();

        // TODO: test validations
    }
    
}
