jobs:
  sync-client-pom:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install xmlstarlet
        run: sudo apt-get update && sudo apt-get install -y xmlstarlet

      - name: Extract parent pom values
        id: extract
        run: |
          PARENT_GROUP_ID=$(xmlstarlet sel -N x="http://maven.apache.org/POM/4.0.0" \
            -t -v "/x:project/x:groupId" pom.xml)
          PARENT_ARTIFACT_ID=$(xmlstarlet sel -N x="http://maven.apache.org/POM/4.0.0" \
            -t -v "/x:project/x:artifactId" pom.xml)
          PARENT_VERSION=$(xmlstarlet sel -N x="http://maven.apache.org/POM/4.0.0" \
            -t -v "/x:project/x:version" pom.xml)

          echo "groupId=$PARENT_GROUP_ID" >> $GITHUB_OUTPUT
          echo "artifactId=$PARENT_ARTIFACT_ID" >> $GITHUB_OUTPUT
          echo "version=$PARENT_VERSION" >> $GITHUB_OUTPUT
