name: Update Client POM

on:
  push:
    # branches:
    #   - main
  workflow_dispatch:

jobs:
  update-pom:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install xmlstarlet
        run: sudo apt-get update && sudo apt-get install -y xmlstarlet

      - name: Extract values from root pom
        id: extract
        run: |
          PRIMARY_POM="pom.xml"

          GROUP_ID=$(xmlstarlet sel -N x="http://maven.apache.org/POM/4.0.0" \
            -t -v "/x:project/x:groupId" $PRIMARY_POM)

          ARTIFACT_ID=$(xmlstarlet sel -N x="http://maven.apache.org/POM/4.0.0" \
            -t -v "/x:project/x:artifactId" $PRIMARY_POM)

          VERSION=$(xmlstarlet sel -N x="http://maven.apache.org/POM/4.0.0" \
            -t -v "/x:project/x:version" $PRIMARY_POM)

          SPRING_BOOT_VERSION=$(xmlstarlet sel -N x="http://maven.apache.org/POM/4.0.0" \
            -t -v "/x:project/x:parent/x:version" $PRIMARY_POM)

          echo "Extracted values:"
          echo "  groupId=$GROUP_ID"
          echo "  artifactId=$ARTIFACT_ID"
          echo "  version=$VERSION"
          echo "  springBootVersion=$SPRING_BOOT_VERSION"

          echo "groupId=$GROUP_ID" >> $GITHUB_ENV
          echo "artifactId=$ARTIFACT_ID" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_ENV
          echo "springBootVersion=$SPRING_BOOT_VERSION" >> $GITHUB_ENV

      - name: Update client pom
        run: |
          SECONDARY_POM="client-code/pom.xml"

          xmlstarlet ed -L \
            -u "/x:project/x:properties/x:spring-boot-version" -v "$springBootVersion" \
            -u "/x:project/x:groupId" -v "$groupId" \
            -u "/x:project/x:artifactId" -v "${artifactId}-client" \
            -u "/x:project/x:version" -v "$version" \
            $SECONDARY_POM

          echo "Updated client POM (client-code/pom.xml):"
          cat $SECONDARY_POM

      # - name: Commit and push changes
      #   run: |
      #     git config user.name "github-actions"
      #     git config user.email "github-actions@github.com"
      #     git add client-code/pom.xml
      #     if git diff --cached --quiet; then
      #       echo "No changes to commit"
      #     else
      #       git commit -m "Auto-update client-code/pom.xml from root pom.xml"
      #       git push
      #     fi
