name: Update Secondary POM

on:
  push:
  workflow_dispatch:

jobs:
  update-pom:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install xmlstarlet
        run: sudo apt-get install -y xmlstarlet

      - name: Define Spring Boot Version
        run: echo "SPRING_BOOT_VERSION=3.5.4" >> $GITHUB_ENV

      - name: Extract values from primary pom.xml
        run: |
          PARENT_GROUP_ID=$(xmlstarlet sel -N x="http://maven.apache.org/POM/4.0.0" \
            -t -v "/x:project/x:groupId" pom.xml)
          PARENT_ARTIFACT_ID=$(xmlstarlet sel -N x="http://maven.apache.org/POM/4.0.0" \
            -t -v "/x:project/x:artifactId" pom.xml)
          PARENT_VERSION=$(xmlstarlet sel -N x="http://maven.apache.org/POM/4.0.0" \
            -t -v "/x:project/x:version" pom.xml)
          PARENT_PACKAGING=$(xmlstarlet sel -N x="http://maven.apache.org/POM/4.0.0" \
            -t -v "/x:project/x:packaging" pom.xml)

          echo "PARENT_GROUP_ID=$PARENT_GROUP_ID" >> $GITHUB_ENV
          echo "PARENT_ARTIFACT_ID=$PARENT_ARTIFACT_ID" >> $GITHUB_ENV
          echo "PARENT_VERSION=$PARENT_VERSION" >> $GITHUB_ENV
          echo "PARENT_PACKAGING=$PARENT_PACKAGING" >> $GITHUB_ENV

      - name: Update secondary pom.xml
        run: |
          # Update Spring Boot version manually
          xmlstarlet ed --inplace \
            -u "/x:project/x:properties/x:spring-boot-version" \
            -v "$SPRING_BOOT_VERSION" client-code/pom.xml \
            -N x="http://maven.apache.org/POM/4.0.0"

          # Update groupId, artifactId, version, packaging from parent pom
          xmlstarlet ed --inplace \
            -u "/x:project/x:groupId" -v "$PARENT_GROUP_ID" \
            -u "/x:project/x:artifactId" -v "MyrishuService-client" \
            -u "/x:project/x:version" -v "$PARENT_VERSION" \
            -u "/x:project/x:packaging" -v "$PARENT_PACKAGING" \
            -N x="http://maven.apache.org/POM/4.0.0" client-code/pom.xml

      - name: Print updated secondary pom.xml
        run: cat client-code/pom.xml

      # - name: Commit and push changes
      #   run: |
      #     git config --global user.name "github-actions"
      #     git config --global user.email "github-actions@github.com"
      #     git add client-code/pom.xml
      #     git commit -m "Update secondary pom.xml from parent pom.xml"
      #     git push